import { Provider } from "react-redux";
import store from "../redux/store";

import "./index.css";

import type { Metadata } from "next";

import Providers from "../redux/provider";
import Layout from "@/components/layouts/Layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): React.ReactNode {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Layout>{children}</Layout>
        </Providers>
      </body>
    </html>
  );
}
